package com.unknownman.core;
public enum UnknownManState { DORMANT, OBSERVING, STALKING, HIDING, INVESTIGATING, REPOSITIONING, APPROACHING, CHASE, ATTACK, RETREAT, SEARCHING, CONFUSED, SCRIPTED_EVENT, FINAL_HUNT, FINAL_BOSS }
